### ISSUE TITLE
Why substracting noise from x instead of adding noise

### ISSUE THREAD

**Issue by cloudseasail** [ysharma1126/caad_18#1]
When updating x,  I can see there is substraction with noise.
wondering should we use adding here?  because we like to increase the loss function,  don't we?
`x = x - alpha * tf.clip_by_value(tf.round(noise), -2, 2)`

**Comment by ysharma1126** [comment]
The return value of ```noise``` updates the ```grad``` argument in ```tf.while_loop()```.

**Comment by cloudseasail** [comment]
> The return value of `noise` updates the `grad` argument in `tf.while_loop()`.

Thanks,  I just noticed,  it is a invalid question,  so I update this thread to a new question,  thanks for replying

**Comment by ysharma1126** [comment]
In the non-targeted case, the loss function is defined with respect to the true label, so as you would like to maximize that loss, you add. In the targeted case, the loss function is defined with respect to the target class, as you would like to minimize that loss, you subtract.

**Comment by cloudseasail** [comment]
> In the non-targeted case, the loss function is defined with respect to the true label, so as you would like to maximize that loss, you add. In the targeted case, the loss function is defined with respect to the target class, as you would like to minimize that loss, you subtract.

Oh, yes you are right.   thanks a lot!
