### ISSUE TITLE
Code of training process about non-targeted attack

### ISSUE THREAD

**Issue by cshanjiewu** [ysharma1126/caad_18#2]
Thanks for sharing this amazing code. I am confused about how to train this net. So if it is possible, can you share the code of nontargeted attack.

**Comment by cshanjiewu** [comment]
code of training process

**Comment by ysharma1126** [comment]
The nets are pretrained and downloaded with ```download_data.sh```.

**Comment by ysharma1126** [comment]
We used the pretrained ATN from https://github.com/pfnet-research/nips17-adversarial-attack. Unfortunately, the training code is not available. See here for details (https://preferredresearch.jp/2018/04/20/nips17-adversarial-learning-competition/).

**Comment by cshanjiewu** [comment]
Thanks for your reply!
